### ISSUE TITLE
Guide for building parsers?

### ISSUE THREAD

**Issue by Shpigford** [Faveod/tree-sitter-parsers#12]
Is there a guide for how to build parsers or get them added to this?

For instance, would love to get typescript added: https://github.com/tree-sitter/tree-sitter-typescript

I've gone through the Tree-sitter docs: https://tree-sitter.github.io/tree-sitter/creating-parsers#command-build

But generating for multiple platforms (macOS + Linux, for instance), is proving pretty difficult.

Would love to add more to this project, just not sure the right way to go about it.

**Comment by stackmystack** [comment]
Hi,

The reason this repo exists is now to serve as an example for [tsdl](https://github.com/stackmystack/tsdl); it used to have ad-hoc scripts to download and build parsers.

Use tsdl to download all parsers configured in a toml, or command line, if you like to override config in different contexts.

tsdl has examples on how to build typescript.

It's written in rust, mostly as an excuse to put my hands into rust; you'll find some needless complexities. Your contributions are more than welcome on tsdl.
